# web port
server:
  port: 8081

# log config
logging:
  config: classpath:logback.xml
  path: ./applogs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:9527
    executor:
      appname: datax-executor
      ip:
      port: 9999
      ### job log path
      logpath: ./applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: /Users/jack/Downloads/apps/datax/tmp
    pythonpath: /usr/bin/python

  pypath: /Users/jack/Downloads/apps/datax/bin/datax.py