# web port
server:
  port: 8081

# log config
logging:
  config: classpath:logback.xml
  path: /data/applogs/executor/jobhandler

### datax admin address list, such as "http://address" or "http://address01,http://address02"
datax:
  job:
    admin:
      ### datax-web admin address
      addresses: http://172.16.1.26:8080
    executor:
      appname: datax-executor
      ip:
      port: 9998
      ### job log path
      logpath: /data/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: /home/executor/json

  pypath: /home/datax-3.0.2/bin/datax.py